### ISSUE TITLE
Implement JAX automatic differentiation on Turboflow

### ISSUE THREAD

**Issue by RoberAgro** [turbo-sim/turboflow#11] opened 2024-10-19 17:52 UTC
- [x] Mathematics functions
- [x] Velocity triangle functions
- [x] Cascade functions
- [x] Loss model functions
  - [x] Isentropic (start with this one)
  - [x] Benner loss model
- [x] Deviation model functions
- [x] Overall turbine calculation
- [x] Performance Analysis
- [x] Design Optimization

**Comment by SrinivasDiwanji** [comment] 2024-10-30 15:01
Verified the gradients for all the cascade functions and also for evaluate_axial_turbine

Educated guess still required to get meaningful derivative values for comparison

**Comment by SrinivasDiwanji** [comment] 2024-11-02 22:05
Pandas dataframe usage has been removed in performance analysis. It has been replaced by dictionaries and other functions decribed in numerics and file_utils docs

**Comment by SrinivasDiwanji** [comment] 2024-11-02 22:08
Writing and storing the results gives errors as it uses pandas commands. This has to be updated and changed.

**Comment by SrinivasDiwanji** [comment] 2024-11-05 15:28
Jax works with isentropic and critical mach choking criteira for the complete axial turbine problem

**Comment by SrinivasDiwanji** [comment] 2024-11-05 15:30
The issue is with critical mass flow rate choking criteria for which jax is not working.
Jax differentiates compute_critical_values function in choking criteria but Jax fails when differentiating critical_mass_flow_rate function

**Comment by SrinivasDiwanji** [comment] 2024-11-05 16:09
Jax runs for critical_mach_number and kacker-okapuu loss model

**Comment by SrinivasDiwanji** [comment] 2024-11-05 17:58
Jax runs for whole turbine calculation with critical_mach_number and moustapha loss model

**Comment by SrinivasDiwanji** [comment] 2024-11-07 08:35
JAX works for two_stage turbine calculation too with crtical_mach_number as choking criterion and all loss models.
Now the issue is with critical_mass_flow_rate choking criterion, it has a tracing error with JAX. One possible issue is with how the function is defined. Checking the issue

**Comment by SrinivasDiwanji** [comment] 2024-11-07 10:27
JAX works now with critical_mass_flow_rate choking criterion too. The tracer error was due to the fact that critical_state was initialized within the critical_mass_flow_rate function and it was being updated which caused the tracer error while using JAX. It is resolved by using another dict updated_critical_state to avoid mutation of critical_state. The updated code works now

**Comment by SrinivasDiwanji** [comment] 2024-11-07 14:05
Performance analysis differentiation with JAX has been done

**Comment by SrinivasDiwanji** [comment] 2024-11-09 17:07
Design Optimization works with critical mach number and approx derivatives

**Comment by SrinivasDiwanji** [comment] 2024-11-11 13:53
len() doesn't work with jax array

**Closed** 2024-11-18 10:57 UTC
